// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjAei-i1-BpjI8gEiIVHhnSk_N8HfE7Sg',
    appId: '1:560333948071:web:82d6671c2dda4c78594782',
    messagingSenderId: '560333948071',
    projectId: 'cryptonian-8d35a',
    authDomain: 'cryptonian-8d35a.firebaseapp.com',
    storageBucket: 'cryptonian-8d35a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfZwQeErIbNA8N1WhIKKzNrfd0mcUR2k',
    appId: '1:560333948071:android:1d975cf874eb7812594782',
    messagingSenderId: '560333948071',
    projectId: 'cryptonian-8d35a',
    storageBucket: 'cryptonian-8d35a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1oJd1-OVLDVZaj2tjqMQRlq7d9fekDw',
    appId: '1:560333948071:ios:8c8fd2bd5d2b7ae9594782',
    messagingSenderId: '560333948071',
    projectId: 'cryptonian-8d35a',
    storageBucket: 'cryptonian-8d35a.appspot.com',
    iosClientId: '560333948071-6bq5frasmhgdg9nmt6s6s4nas2jrkhmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptonian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA1oJd1-OVLDVZaj2tjqMQRlq7d9fekDw',
    appId: '1:560333948071:ios:8c8fd2bd5d2b7ae9594782',
    messagingSenderId: '560333948071',
    projectId: 'cryptonian-8d35a',
    storageBucket: 'cryptonian-8d35a.appspot.com',
    iosClientId: '560333948071-6bq5frasmhgdg9nmt6s6s4nas2jrkhmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptonian',
  );
}
